import type { APIRoute } from 'astro';

// Dynamic robots.txt — allows all crawlers and points to the sitemap index
// generated by @astrojs/sitemap. The sitemap URL is built from the `site`
// config so it stays correct across environments.
export const GET: APIRoute = ({ site }) => {
  const sitemapUrl = new URL('sitemap-index.xml', site).href;

  const body = `User-agent: *
Allow: /

Sitemap: ${sitemapUrl}
`;

  return new Response(body, {
    headers: { 'Content-Type': 'text/plain; charset=utf-8' },
  });
};
